# Generated by Django 5.2.7 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Рекрутер'), ('manager', 'Менеджер'), ('administrator', 'Администратор')], default='recruiter', max_length=20),
        ),
    ]
