# Generated by Django 5.2.7 on 2025-11-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Рекрутер'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='recruiter', max_length=20),
        ),
    ]
