# Generated by Django 5.2.7 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelform',
            name='skills',
            field=models.ManyToManyField(blank=True, to='vacancies.skill', verbose_name='Навыки'),
        ),
    ]
