# Generated by Django 5.2.6 on 2025-09-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_options_candidate_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
