# Generated by Django 5.2.7 on 2025-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Место рождения')),
                ('citizenship', models.CharField(default='Российская Федерация', max_length=100, verbose_name='Гражданство')),
                ('address', models.TextField(verbose_name='Адрес проживания')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('education', models.CharField(choices=[('secondary', 'Среднее'), ('specialized_secondary', 'Среднее специальное'), ('incomplete_higher', 'Неполное высшее'), ('higher', 'Высшее'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат наук'), ('doctor', 'Доктор наук')], max_length=50, verbose_name='Образование')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность по диплому')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('marital_status', models.CharField(choices=[('single', 'Холост/Не замужем'), ('married', 'Женат/Замужем'), ('divorced', 'Разведен(а)'), ('widowed', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.TextField(verbose_name='Кем выдан')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('passport_department_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('military_duty', models.BooleanField(default=False, verbose_name='Военнообязанный')),
                ('military_rank', models.CharField(blank=True, max_length=50, verbose_name='Воинское звание')),
                ('military_specialty', models.CharField(blank=True, max_length=100, verbose_name='Военно-учетная специальность')),
                ('work_experience_total', models.PositiveIntegerField(verbose_name='Общий стаж работы (лет)')),
                ('work_experience_specialty', models.PositiveIntegerField(verbose_name='Стаж работы по специальности (лет)')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Проверено отделом кадров')),
            ],
            options={
                'verbose_name': 'Анкета сотрудника',
                'verbose_name_plural': 'Анкеты сотрудников',
                'ordering': ['-created_at'],
            },
        ),
    ]
