# Generated by Django 5.2.7 on 2025-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_personnelform_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='desired_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Желаемая зарплата'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Трудоустроен'), ('unemployed', 'В поиске'), ('part_time', 'Частичная занятость')], default='unemployed', max_length=20, verbose_name='Статус трудоустройства'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок выхода на работу'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20, verbose_name='Уровень позиции'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_format',
            field=models.CharField(blank=True, choices=[('office', 'Офис'), ('remote', 'Удаленно'), ('hybrid', 'Гибрид')], max_length=20, verbose_name='Формат работы'),
        ),
    ]
