# Generated by Django 5.2.7 on 2025-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_desired_salary_candidate_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assigned_recruiter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ответственный рекрутер'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_features',
            field=models.TextField(blank=True, verbose_name='Особенности кандидата'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='ВУЗ/Курсы'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Среднее'), ('specialized_secondary', 'Среднее специальное'), ('incomplete_higher', 'Неполное высшее'), ('higher', 'Высшее'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат наук'), ('doctor', 'Доктор наук')], max_length=50, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_workplace',
            field=models.CharField(blank=True, max_length=200, verbose_name='Последнее место работы'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='next_actions',
            field=models.TextField(blank=True, verbose_name='План следующих действий'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter_notes',
            field=models.TextField(blank=True, verbose_name='Примечания рекрутера'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Обязанности и достижения'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('hh', 'HH.ru'), ('linkedin', 'LinkedIn'), ('habr', 'Habr Career'), ('recommendation', 'Рекомендация'), ('other', 'Другое')], default='hh', max_length=100, verbose_name='Источник кандидата'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='Детали источника'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='Период работы'),
        ),
    ]
