# Generated by Django 5.2.7 on 2025-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Трудоустроен'), ('unemployed', 'В поиске'), ('part_time', 'Частичная занятость'), ('student', 'Студент')], default='unemployed', max_length=20, verbose_name='Статус трудоустройства'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position_level',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20, verbose_name='Уровень позиции'),
        ),
    ]
