# Generated by Django 5.2.7 on 2025-10-31 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidate_employment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарий рекрутера'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Дата и время собеседования')),
                ('interview_type', models.CharField(choices=[('phone', '📞 Телефонное'), ('video', '🎥 Видео-собеседование'), ('in_person', '👥 Личная встреча'), ('technical', '💻 Техническое'), ('hr', '👔 HR-собеседование')], max_length=20, verbose_name='Тип собеседования')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Кандидат не явился')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('feedback', models.TextField(blank=True, verbose_name='Отзыв после собеседования')),
                ('result', models.CharField(blank=True, choices=[('positive', 'Положительный'), ('negative', 'Отрицательный'), ('neutral', 'Нейтральный')], max_length=20, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запланировал')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
