# Generated by Django 5.2.7 on 2025-10-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_application_notes_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания'),
        ),
        migrations.AddField(
            model_name='interview',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
    ]
