# Generated by Django 5.2.7 on 2025-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_interview_reminder_date_interview_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelform',
            name='candidate_status',
            field=models.CharField(choices=[('new', 'Новый'), ('reviewed', 'Рассмотрен'), ('interviewed', 'Собеседование пройдено'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус кандидата'),
        ),
    ]
