# Generated by Django 5.2 on 2025-11-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_personnelform_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelform',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_form', to='candidates.candidate', verbose_name='Кандидат'),
        ),
    ]
