# Generated by Django 5.2.7 on 2025-10-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='assigned_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный рекрутер'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость')], default='full_time', max_length=50, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('office', 'Офис'), ('remote', 'Удаленно'), ('hybrid', 'Гибрид')], default='office', max_length=10, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
